### PR TITLE
treat benchmarks as normal tests

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

Last I checked this behavior is consistent with cargo test. Bench cases that appear in test binary list should be considered a normal test.

### CODE REVIEW

**Comment by sunshowers** [comment]
Thanks for the PR!

What happens if a benchmark is invoked? Is it run just once or many times?

Note that the most popular benchmarking library criterion.rs doesn't currently work with nextest: https://github.com/bheisler/criterion.rs/issues/562

**Comment by tabokie** [comment]
@sunshowers In the case of `cargo test`, all `#[bench]` benches will behave just like normal unit tests (run just once). They will be run even if `--tests` is passed. Cases managed by `criterion.rs` will not be run, because they are not contained in the test binary generated by `cargo test`.

**Comment by sunshowers** [comment]
Thanks -- in that case this makes sense. I'll add a note to the release notes explaining that criterion still won't work but at least it won't break due to this.

**Comment by sunshowers** [comment]
This is now out as cargo-nextest 0.9.22 (binaries will be out shortly).

**Pull request merged**
