### PR TITLE
Update baptiste0928/cargo-install action to v2

### PR DESCRIPTION
**Pull request by sunshowers**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [baptiste0928/cargo-install](https://togithub.com/baptiste0928/cargo-install) | action | major | `v1` -> `v2` |

---

### Release Notes

<details>
<summary>baptiste0928/cargo-install (baptiste0928/cargo-install)</summary>

### [`v2`](https://togithub.com/baptiste0928/cargo-install/compare/v1...v2)

[Compare Source](https://togithub.com/baptiste0928/cargo-install/compare/v1...v2)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 8pm,before 6am" in timezone America/Los_Angeles, Automerge - "after 8pm,before 6am" in timezone America/Los_Angeles.

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by NobodyXu** [comment]
P.S. Why not use https://github.com/taiki-e/install-action for installing pre-built binaries?
It could also take advantages of cargo-binstall

**Comment by sunshowers** [comment]
@NobodyXu mostly because that hadn't been done yet.

**Comment by sunshowers** [comment]
@NobodyXu actually, one reason is that `taiki-e/install-action` can't perform caching for installed binaries. Also, the quickinstall integration might be busted?

```
% cargo binstall cargo-release@=0.21.4
 WARN Failed to read git credential file /home/rain/.git-credentials err=Os { code: 2, kind: NotFound, message: "No such file or directory" }
 INFO resolve: Resolving package: 'cargo-release@=0.21.4'
 WARN The package cargo-release v0.21.4 will be installed from source (with cargo)
Do you wish to continue? yes/[no]
?  WARN Failed to send quickinstall report for package cargo-release-0.21.4-x86_64-unknown-linux-musl: Failed to download from remote: could not HEAD https://warehouse-clerk-tmp.vercel.app/api/crate/cargo-release-0.21.4-x86_64-unknown-linux-musl.tar.gz: HTTP status server error (500 Internal Server Error) for url (https://warehouse-clerk-tmp.vercel.app/api/crate/cargo-release-0.21.4-x86_64-unknown-linux-musl.tar.gz)
 WARN Failed to send quickinstall report for package cargo-release-0.21.4-x86_64-unknown-linux-gnu: Failed to download from remote: could not HEAD https://warehouse-clerk-tmp.vercel.app/api/crate/cargo-release-0.21.4-x86_64-unknown-linux-gnu.tar.gz: HTTP status server error (500 Internal Server Error) for url (https://warehouse-clerk-tmp.vercel.app/api/crate/cargo-release-0.21.4-x86_64-unknown-linux-gnu.tar.gz)
^C WARN Installation cancelled

% cargo binstall -V
1.4.2
```

**Comment by sunshowers** [comment]
https://github.com/nextest-rs/nextest/pull/1005#issuecomment-1741747433 should address this (partially).

**Comment by sunshowers** [comment]
Going to close this and let renovate generate a new one.

**Comment by NobodyXu** [comment]
@sunshowers You can use actions/cache@v4 directly to cache `~/.cargo/.crates*` (`.crates.toml` and `.crates2.json`) and `~/.cargo/bin`, it will cache all binaries installed and `cargo-binstall` would skip installing any crate that is installed and up-to-date.

Regading the error, it might be spurious.
However if it persists, please ping me and I will investigate this.

**Pull request closed without merging**
