### PR TITLE
generalize slow-timeout.grace-period to all shutdown events

### PR DESCRIPTION
**Pull request by kallisti-dev**
Implementation for #931

Removes `slow-timeout.grace-period` and replaces it with `shutdown-grace-period` at the top-level config. The new config value applies to all shutdown events.

### CODE REVIEW

**Comment by kallisti-dev** [comment]
Should we mention the new behavior on ctrl+c and other shutdown events somewhere in the book? I wasn't sure where would be an appropriate place to mention the added behavior.

**Comment by sunshowers** [comment]
Thanks. I'll get to reviewing this next week, but a quick comment is that we cannot break compatibility. If slow-timeout.grace-period is mentioned, it shouldn't be ignored.

A thing that would probably be reasonable to do is to preferentially use shutdown-grace-period but still support the old value.

**Comment by sunshowers** [comment]
Another option is to just use slow-timeout.grace-period for shutdown grace periods as well. I think that might end up being simpler overall.

**Comment by kallisti-dev** [comment]
> Thanks. I'll get to reviewing this next week, but a quick comment is that we cannot break compatibility. If slow-timeout.grace-period is mentioned, it shouldn't be ignored.

The new docs don't mention it anywhere, but I agree that compatibility should be maintained if possible.
 
> A thing that would probably be reasonable to do is to preferentially use shutdown-grace-period but still support the old value.

My initial thought was to have `slow-timeout.grace-period` overlap on top of `shutdown-grace-period` and specifically only handle the timeout events instead of all shutdown events, thus preserving the old behavior, but this seemed unnecessarily complicated and could be difficult to explain in documentation. Having them being aliases of each other for compatibility, with precedence for the new value, makes sense and is a simple change.

**Comment by sunshowers** [comment]
> Much simpler from the perspective of an existing user, but it does hide the fact that the grace-period affects more than just timeout events.

Personally I think that's fine to be honest. I don't really see a distinction between a test shutting down because of a timeout and a test shutting down because a user hit ctrl-c.

Definitely aiming for simplicity in this case.

**Comment by kallisti-dev** [comment]
Sounds good. I'll update the PR to go back to using slow-timeout.grace-period

**Comment by kallisti-dev** [comment]
Updated

**Comment by sunshowers** [comment]
Looks good, thanks! I'll get this out within the next 1-2 days.

**Comment by sunshowers** [comment]
Released as part of nextest 0.9.61.

**Pull request merged**
