### PR TITLE
Refactor: Simplify `select!` code and replace confusing `*_done` `boolean`s with `FusedFuture`

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by sunshowers** [comment]
Thanks! I don't think this is quite correct—we definitely need to loop until either the timer is hot or stdout and stderr are both closed

**Comment by sunshowers** [comment]
I'm also honestly not a fan of the fused future in this case, since you have to check if they're terminated anyway it just adds verbosity.

**Comment by NobodyXu** [comment]
> Thanks! I don't think this is quite correct—we definitely need to loop until either the timer is hit or stdout and stderr are both closed.

I created a new future `collect_output_fut` which `try_join` both `stdout_fut` and `stderr_fut`, so that we don't need to poll for both variable.

Since we only need to poll `collect_output_fut` and `sleep`in the second `select!`, there's no need for the loop.
We simply let them race to completion and pick the one that completes first and return `false` or `true` correspondingly.

**Comment by NobodyXu** [comment]
> I'm also honestly not a fan of the fused future in this case, since you have to check if they're terminated anyway it just adds verbosity.

I would argue it is still an improvement.

Before that, we would check `*_done` in every `select!` statement, while now we only checked it once before the second `select!`.

Also, using fused future in select is actually the easy way to go and is more readable if you want to poll the same future multiple times, I read somewhere that they actually argue that all futures used in `select!` should be fused or print out an error.

With `fused`, you know immediately that this branch is simply ignored once it is completed and would not panic at runtime or prohibit some UBs.
With boolean flags, you need to actually think about them a while before realizing what it's doing.

**Comment by NobodyXu** [comment]
Actually the second `select!` can be completely replaced by [`tokio::time::Timeout`](https://docs.rs/tokio/latest/tokio/time/struct.Timeout.html) which is more ergonomic than `select!`.

**Comment by NobodyXu** [comment]
> Actually the second `select!` can be completely replaced by [`tokio::time::Timeout`](https://docs.rs/tokio/latest/tokio/time/struct.Timeout.html) which is more ergonomic than `select!`.

Done!

Now it is even more simpler.

**Comment by sunshowers** [comment]
Thanks but I'm afraid I'm going to have to reject this again. I actually have some WIP code that needs the second select to be as it is, since it also selects across a channel in addition to the existing futures.

As I said I'm still not a fan of FusedFuture in cases where the code behaves differently based on whether the future has terminated. In the end it's a matter of taste, and as the maintainer I like the current approach more. Unless there's a clear correctness or performance issue, I think minor refactoring like this is just not that useful.

**Comment by NobodyXu** [comment]
Got it, I will close this PR.

**Comment by sunshowers** [comment]
BTW this thread and specifically this comment might be interesting: https://users.rust-lang.org/t/why-doesnt-tokio-select-require-fusedfuture/46975/13

**Pull request closed without merging**
