### PR TITLE
docs: add coverage support

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

close https://github.com/nextest-rs/nextest/issues/56

PTAL, thanks! cc @sunshowers

### CODE REVIEW

**Comment by skyzh** [comment]
We can also wait for llvm-cov to release a stable version, so that we don't need to install from git...

**Comment by sunshowers** [comment]
Thank you for getting this done upstream!

Looks like Taiki added nextest to his install action -- would like to work with him on a small fixup and then update docs to point to that.

**Comment by sunshowers** [comment]
Let's get https://github.com/taiki-e/install-action/pull/3 in then land this! Thanks again.

**Comment by sunshowers** [comment]
Going to land this then edit it a bit. Thanks again!

**Pull request merged**
