### PR TITLE
Add Homebrew install instructions

### PR DESCRIPTION
**Pull request by rouge8**
I added cargo-nextest to Homebrew :)

### CODE REVIEW

**Comment by sunshowers** [comment]
Wow, thank you!

Are you going to maintain it as new versions come out? I'm a little worried about nextest falling behind.

**Comment by sunshowers** [comment]
Also, thanks for using the default-no-update feature! This is exactly what it's for.

**Comment by rouge8** [comment]
> Wow, thank you!
> 
> Are you going to maintain it as new versions come out? I'm a little worried about nextest falling behind.

Sure I can try!

**Comment by sunshowers** [comment]
I think this should be on the "Installing from source" page because the Homebrew formula https://github.com/Homebrew/homebrew-core/pull/105954 (like most Homebrew formulas) does a source install.

**Comment by rouge8** [comment]
The PR is a source install, but when they merge they add bottles so it’s installed from binaries.

**Comment by sunshowers** [comment]
Oh right. That makes sense.

Thanks again, will merge later today.

**Comment by sunshowers** [comment]
Thanks again!

**Pull request merged**
